version: '3.5'

services:
  frontend:
    build:
      dockerfile:  Dockerfile
      context: .
    ports:
      - "3001:3000"
    command: yarn start
    volumes:
      #      will cache node_modules
      - /app/node_modules
      #      check host changes
      - ./src:/app/src
